export const TOGGLE_DRAWER_STATE = "TOGGLE_DRAWER_STATE"

export const RESET_APP = "RESET_APP"

export const SET_PRIMARY_COLOR = "SET_PRIMARY_COLOR"

export const ON_SAVE_PRIMARY_COLOR = "ON_SAVE_PRIMARY_COLOR"

export const ON_SAVE_PRIMARY_COLOR_RESPONSE = "ON_SAVE_PRIMARY_COLOR_RESPONSE"

export const RESET_SAVE_PRIMARY_COLOR = "RESET_SAVE_PRIMARY_COLOR"
