export const ON_LOGIN = "ON_LOGIN"

export const ON_LOGIN_RESPONSE = "ON_LOGIN_RESPONSE"

export const ON_REGISTER = "ON_REGISTER"

export const ON_REGISTER_RESPONSE = "ON_REGISTER_RESPONSE"

export const RESET_AUTH = "RESET_AUTH"

export const ON_GET_USER_INFO = "ON_GET_USER_INFO"

export const ON_GET_USER_INFO_RESPONSE = "ON_GET_USER_INFO_RESPONSE"

export const ON_UPLOAD_PROFILE_PHOTO = "ON_UPLOAD_PROFILE_PHOTO"

export const ON_UPLOAD_PROFILE_PHOTO_RESPONSE =
  "ON_UPLOAD_PROFILE_PHOTO_RESPONSE"
