

export const ON_LOGIN = "ON_LOGIN"

export const ON_LOGIN_RESPONSE = "ON_LOGIN_RESPONSE"

export const ON_REGISTER = "ON_REGISTER"

export const ON_REGISTER_RESPONSE = "ON_REGISTER_RESPONSE"

export const RESET_AUTH = "RESET_AUTH"

