export const ON_LOGIN = "ON_LOGIN"

export const ON_LOGIN_RESPONSE = "ON_LOGIN_RESPONSE"

export const ON_REGISTER = "ON_REGISTER"

export const ON_REGISTER_RESPONSE = "ON_REGISTER_RESPONSE"

export const RESET_AUTH = "RESET_AUTH"

export const ON_GET_USER_INFO = "ON_GET_USER_INFO"

export const ON_GET_USER_INFO_RESPONSE = "ON_GET_USER_INFO_RESPONSE"

export const ON_UPLOAD_PROFILE_PHOTO = "ON_UPLOAD_PROFILE_PHOTO"

export const ON_UPLOAD_PROFILE_PHOTO_RESPONSE =
  "ON_UPLOAD_PROFILE_PHOTO_RESPONSE"

export const ON_UPDATE_PROFILE_BASIC = "ON_UPDATE_PROFILE_BASIC"

export const ON_UPDATE_PROFILE_BASIC_RESPONSE =
  "ON_UPDATE_PROFILE_BASIC_RESPONSE"

export const RESET_UPDATE_PROFILE_DATA = "RESET_UPDATE_PROFILE_DATA"

export const ON_UPDATE_PROFILE_PASSWORD = "ON_UPDATE_PROFILE_PASSWORD"

export const ON_UPDATE_PROFILE_PASSWORD_RESPONSE =
  "ON_UPDATE_PROFILE_PASSWORD_RESPONSE"

export const ON_CLOSE_ACCOUNT = "ON_CLOSE_ACCOUNT"

export const ON_CLOSE_ACCOUNT_RESPONSE = "ON_CLOSE_ACCOUNT_RESPONSE"
