export const ON_NEW_BOARD = "ON_NEW_BOARD"

export const ON_NEW_BOARD_RESPONSE = "ON_NEW_BOARD_RESPONSE"

export const RESET_BOARD = "RESET_BOARD"

export const ON_GET_ALL_BOARD = "ON_GET_ALL_BOARD"
export const ON_GET_ALL_BOARD_RESPONSE = "ON_GET_ALL_BOARD_RESPONSE"

export const ON_GET_BOARD_BY_ID = "ON_GET_BOARD_BY_ID"
export const GET_BOARD_BY_ID_RESPONSE = "GET_BOARD_BY_ID_RESPONSE"
export const ON_BOARD_SEARCH = "ON_BOARD_SEARCH"
export const ON_BOARD_SEARCH_RESPONSE = "ON_BOARD_SEARCH_RESPONSE"
export const SET_BOARD_HEADER_TITLE = "SET_BOARD_HEADER_TITLE"

