export const ON_NEW_ISSUE = "ON_NEW_ISSUE"

export const ON_NEW_ISSUE_RESPONSE = "ON_NEW_ISSUE_RESPONSE"

export const RESET_ISSUE = "RESET_ISSUE"

export const ON_GET_ALL_ISSUE_RESPONSE = "ON_GET_ALL_ISSUE_RESPONSE"

export const ON_GET_ALL_ISSUE = "ON_GET_ALL_ISSUE"

export const ON_GET_ISSUE_BY_ID = "ON_GET_ISSUE_BY_ID"

export const GET_ISSUE_BY_ID_RESPONSE = "GET_ISSUE_BY_ID_RESPONSE"

export const ON_ISSUE_SEARCH = "ON_ISSUE_SEARCH"

export const ON_ISSUE_SEARCH_RESPONSE = "ON_ISSUE_SEARCH_RESPONSE"

export const SET_ISSUE_HEADER_TITLE = "SET_ISSUE_HEADER_TITLE"

