



export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGIN_SUCCESSFULL = 'ON_LOGIN_SUCCESSFULL';
export const ON_LOGIN_FAILED = 'ON_LOGIN_FAILED';

export const ON_REGISTER = 'ON_REGISTER';
export const ON_REGISTER_SUCCESSFULL = 'ON_REGISTER_SUCCESSFULL';
export const ON_REGISTER_FAILED = 'ON_REGISTER_FAILED';

